name: POOPY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    # Install Visual Studio Build Tools, CMake, Ninja, and Python using Scoop
    - name: Install Dependencies
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install cmake ninja python

    # Setup Rust toolchain
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rust-src, rustc, cargo

    # Build the project
    - name: Build
      run: cargo build --release

    # Upload the executable as an artifact
    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Veloren Executable
        path: target/release/*.exe
