name: POOPY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        profile: minimal
        override: true

    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64

    - name: Configure Cargo for cross-compilation
      run: |
        echo "[target.x86_64-pc-windows-gnu]" >> $HOME/.cargo/config.toml
        echo "linker = 'x86_64-w64-mingw32-gcc'" >> $HOME/.cargo/config.toml

    - name: Build the project
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload Windows executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: target/x86_64-pc-windows-gnu/release/*.exe
