name: POOPY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-gnu
        profile: minimal
        override: true

    - name: Install MinGW-w64
      run: |
        sudo apt update
        sudo apt install -y mingw-w64
        
    - name: Build the project
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload Windows executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: target/x86_64-pc-windows-gnu/release/*.exe
